### For Tex Live Full: https://github.com/overleaf/toolkit/blob/master/doc/ce-upgrading-texlive.md
## Find out ID of shareleaf container:
# docker ps
## Go inside the shareleaf container:
# docker exec -it <id here> bash
## Freeze tex repo: https://www.tug.org/texlive/acquire.html#past
# tlmgr option repository https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2023/tlnet-final
# tlmgr update --self
# tlmgr install scheme-full
## Opionally install individual packages
# tlmgr install tikzlings tikzmarmots tikzducks
## Freeze image to save in compose:
# docker commit sharelatex sharelatex/sharelatex:with-texlive-full
## In yml write:
# image: sharelatex/sharelatex:with-texlive-full
# Note that you will need to remove this committed container and repeat these steps when you upgrade.
# https://github.com/overleaf/toolkit/blob/master/doc/upgrading.md
# May have bibtex issues: https://github.com/overleaf/overleaf/issues/1030
version: "2.2"
services:
  sharelatex:
    restart: always
    image: hnko/sharelatex
    container_name: overleaf
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - 8888:80
    links:
      - mongo
      - redis
    volumes:
      - /jamleaf/sharelatex_data:/var/lib/sharelatex
    environment:
      SHARELATEX_APP_NAME: JamLab Overleaf CE
      SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex

      # Same property, unfortunately with different names in
      # different locations
      SHARELATEX_REDIS_HOST: redis
      REDIS_HOST: redis

      ENABLED_LINKED_FILE_TYPES: "project_file,project_output_file"

      # Enables Thumbnail generation using ImageMagick
      ENABLE_CONVERSIONS: "true"

      # Disables email confirmation requirement
      EMAIL_CONFIRMATION_DISABLED: "true"

      # temporary fix for LuaLaTex compiles
      # see https://github.com/overleaf/overleaf/issues/695
      TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var

      ## Set for SSL via nginx-proxy
      #VIRTUAL_HOST: 103.112.212.22

      SHARELATEX_SITE_URL: https://overleaf.jamfox.dev
      SHARELATEX_NAV_TITLE: JamLab ShareLaTeX Instance
      # SHARELATEX_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
      SHARELATEX_ADMIN_EMAIL: jamleaf@jamfox.dev

      # SHARELATEX_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://www.sharelatex.com\">ShareLaTeX</a> 2016"},{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
      SHARELATEX_RIGHT_FOOTER: '[{"text": "JamLeaf - JamLab ShareLaTeX Instance"} ]'

      SHARELATEX_EMAIL_FROM_ADDRESS: "jamleaf@jamfox.dev"

      # SHARELATEX_EMAIL_AWS_SES_ACCESS_KEY_ID:
      # SHARELATEX_EMAIL_AWS_SES_SECRET_KEY:

      # SHARELATEX_EMAIL_SMTP_HOST: smtp.mydomain.com
      # SHARELATEX_EMAIL_SMTP_PORT: 587
      # SHARELATEX_EMAIL_SMTP_SECURE: false
      # SHARELATEX_EMAIL_SMTP_USER:
      # SHARELATEX_EMAIL_SMTP_PASS:
      # SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
      # SHARELATEX_EMAIL_SMTP_IGNORE_TLS: false
      # SHARELATEX_EMAIL_SMTP_NAME: '127.0.0.1'
      # SHARELATEX_EMAIL_SMTP_LOGGER: true
      # SHARELATEX_CUSTOM_EMAIL_FOOTER: "This system is run by department x"

  mongoinit:
    image: mongo:4.4
    container_name: overleaf_mongoinit
    # this container will exit after executing the command
    restart: "no"
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint:
      [
        "mongo",
        "--host",
        "mongo:27017",
        "--eval",
        'rs.initiate({ _id: "overleaf", members: [ { _id: 0, host: "mongo:27017" } ] })',
      ]

  mongo:
    restart: always
    image: mongo:4.4
    container_name: overleaf_mongo
    expose:
      - 27017
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /jamleaf/mongo_data:/data/db
    command: --replSet overleaf
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    restart: always
    image: redis:5
    container_name: overleaf_redis
    expose:
      - 6379
    volumes:
      - /jamleaf/redis_data:/data
