version: "3"
services:
  valheim:
    image: mbround18/valheim:sha-f25b81a
    stop_signal: SIGINT
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      PORT: 2456
      NAME: "JamHeim"
      WORLD: "JamWorld"
      PASSWORD: ""
      PRESET: "Normal"
      MODIFIERS: "resources=muchmore"
      # Comment next 2 out for vanilla
      TYPE: "ValheimPlus" 
      MODS: "https://gcdn.thunderstore.io/live/repository/packages/denikson-BepInExPack_Valheim-5.4.2202.zip,https://gcdn.thunderstore.io/live/repository/packages/Advize-CartographySkill-3.0.0.zip,https://gcdn.thunderstore.io/live/repository/packages/Azumatt-Official_BepInEx_ConfigurationManager-18.2.0.zip,https://gcdn.thunderstore.io/live/repository/packages/ValheimPlus-ValheimPlus-9.9.11.zip"
      #WEBHOOK_URL: ""
      WEBHOOK_INCLUDE_PUBLIC_IP: 1
      PUBLIC: 1
      AUTO_UPDATE: 0
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      AUTO_UPDATE_PAUSE_WITH_PLAYERS: 1
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS: 1

      UPDATE_ON_STARTUP: 1
      ADDITIONAL_STEAMCMD_ARGS: "-console"
    volumes:
      - /valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /valheim/server:/home/steam/valheim
      - /valheim/backups:/home/steam/backups