services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TZ: 'Europe/Tallinn'
      # Version variable options:
      # LATEST (the default)
      # SNAPSHOT
      # a specific version, such as "1.7.9"
      # or an alpha and beta version, such as "b1.7.3" (server download might not exist)
      VERSION: 1.20.1
      # https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/
      MOD_PLATFORM: "AUTO_CURSEFORGE"
      # When entering your API Key in a docker compose file you will need to escape any $ character with a second $
      CF_API_KEY: 'CHANGEME'
      # Latest: #'https://www.curseforge.com/minecraft/modpacks/better-beta'
      CF_PAGE_URL: 'https://www.curseforge.com/minecraft/modpacks/better-beta/files/5576692' # 3.2.3
      MODS: |
        https://mediafilez.forgecdn.net/files/5162/837/modmenu-7.2.2.jar
        https://mediafilez.forgecdn.net/files/4586/218/worldedit-mod-7.2.15.jar
        https://mediafilez.forgecdn.net/files/4579/791/imst-2.1.0.jar
        https://mediafilez.forgecdn.net/files/5597/594/Fantastic%20Remastered%20Structures%201.20%2B1.20.6-0.5%20For%2Bfab.jar
        https://cdn.modrinth.com/data/x4MjQT3r/versions/Fm3PgljJ/discoveria-2.0.1.jar
        https://cdn.modrinth.com/data/V6LLU8Gf/versions/9lcqtOok/katters-structures-1.6.jar
        https://cdn.modrinth.com/data/A9XFwNaH/versions/I22FK4xu/just-another-structure-pack-1.5.jar
        https://cdn.modrinth.com/data/InKbRcdX/versions/X8LPgIKP/vanilla-friendly-structures-1.0.6.jar
        https://cdn.modrinth.com/data/HSfsxuTo/versions/WqmT3avQ/Explorify%20v1.6.0%20f10-48.jar
        https://cdn.modrinth.com/data/bii8qPSt/versions/lAWeUicN/ati_structures%281.20%29_v1.1.0_FABRIC.jar
        https://cdn.modrinth.com/data/kL2MnxMQ/versions/UjlSd5DK/i_wanna_travel-fabric-0.2.jar
        https://mediafilez.forgecdn.net/files/4646/391/enchantment-transfer-0.0.6-fabric-1.20.1.jar
        https://cdn.modrinth.com/data/H8CaAYZC/versions/XGIsoVGT/starlight-1.1.2%2Bfabric.dbc156f.jar
        https://cdn.modrinth.com/data/fALzjamp/versions/NHWYq9at/Chunky-1.3.146.jar
        https://cdn.modrinth.com/data/KuNKN7d2/versions/EuQErqo9/noisium-forge-2.0.3%2Bmc1.20-1.20.1.jar
        https://cdn.modrinth.com/data/VSNURh3q/versions/meepZdLs/c2me-fabric-mc1.20.1-0.2.0%2Balpha.11.10.jar
        https://cdn.modrinth.com/data/EEIwvQVo/versions/29RM9vrK/tidal-towns-1.3.jar
        https://cdn.modrinth.com/data/8oi3bsk5/versions/WeYhEb5d/Terralith_1.20.x_v2.5.4.jar
      DATAPACKS: |
        https://cdn.modrinth.com/data/x4MjQT3r/versions/PWPlMf8Z/discoveria-datapack-2.0.1.zip
        https://cdn.modrinth.com/data/V6LLU8Gf/versions/udHMljEk/Katters%20Structures.zip
        https://cdn.modrinth.com/data/A9XFwNaH/versions/6p0dzN83/Just%20Another%20Structure%20Pack%20v1.5.zip
        https://cdn.modrinth.com/data/InKbRcdX/versions/DQcizC1s/%C2%A79V%C2%A7aa%C2%A7bn%C2%A7ci%C2%A7dl%C2%A7el%C2%A79a%20%C2%A7aF%C2%A7br%C2%A7ce%C2%A7di%C2%A7en%C2%A79d%C2%A7al%C2%A7by%20%C2%A7cS%C2%A7dt%C2%A7er%C2%A79u%C2%A7ac%C2%A7bt%C2%A7cu%C2%A7dr%C2%A7ee%C2%A79s_1.20-1.20.6.zip
        https://cdn.modrinth.com/data/HSfsxuTo/versions/haQCGB8I/Explorify%20v1.6.0%20f10-48.zip
        https://cdn.modrinth.com/data/bii8qPSt/versions/8OC8faML/ATi%20StructuresV1.1.0%20%281.20%29%20-%20DATAPACK.zip
        https://cdn.modrinth.com/data/kL2MnxMQ/versions/K6l8e4eC/i_wanna_travel-datapack-0.1.zip
        https://cdn.modrinth.com/data/Dn6ZBPxm/versions/7p9w32nz/StructuresPack%20v1.0.0.zip
        https://cdn.modrinth.com/data/EEIwvQVo/versions/kyK3ZfPm/tidal.zip
      CF_DOWNLOADS_REPO: '/downloads'
      # Mods can be excluded by passing a comma or space delimited list of project slugs or IDs via CF_EXCLUDE_MODS
      # Exclude erroring Abuseless Hardcore 968038
      CF_EXCLUDE_MODS: '968038'
      # Similarly, there are some mods that are incorrectly tagged as client only
      # For those, pass the project slugs or IDs via CF_FORCE_INCLUDE_MODS.
      #CF_FORCE_INCLUDE_MODS: ''
      #CF_FORCE_SYNCHRONIZE: true
      MOTD: |
        JamFox's Better Beta Server!
      EXISTING_WHITELIST_FILE: "SYNCHRONIZE"
      WHITELIST: |
        jamfox
        JobiMollusk
        SergeantRat
        mathiasmarcus99
        Violetic
        SaladPT
        Saage__
        HellHound1717
        beanieb00bie
      OPS: |
        jamfox
      DIFFICULTY: 'hard'
      # To change level type on existing world:
      # 1. Get NBT Studio (or other NBT editor): https://github.com/tryashtar/nbt-studio
      # 2. Generate world with desired world gen algorithm
      # 3. Stop server
      # 4. Open your world and new worlds level.dat in NBT editor
      # 5. Copy 'level-desired.dat > Data > WorldGenSettings > dimensions' to your level.dat
      # 6. Save and reboot 
      LEVEL_TYPE: "NORMAL"
      MAX_PLAYERS: 10
      SPAWN_PROTECTION: 9
      # https://minecraft.wiki/w/Server.properties#level-type
      #LEVEL_TYPE: 'minecraft:default'
      # https://minecraft.wiki/w/Server.properties#generator-settings
      #GENERATOR_SETTINGs:
      SERVER_NAME: 'JamFox Better Beta Server'
      #RCON_PASSWORD: ''
      RCON_PORT: 25575
      # Autopause when last connect was a while ago
      ENABLE_AUTOPAUSE: true
      # pausing causes a single tick to take as long as the process is stopped, so we disable tick watchdog
      MAX_TICK_TIME: -1
      USE_AIKAR_FLAGS: true
      INIT_MEMORY: '12G'
      MAX_MEMORY: '64G'
      SYNC_CHUNK_WRITES: false
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 6
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /itzg-minecraft/data:/data
      - /itzg-minecraft/downloads:/downloads