services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      # Version variable options:
      # LATEST (the default)
      # SNAPSHOT
      # a specific version, such as "1.7.9"
      # or an alpha and beta version, such as "b1.7.3" (server download might not exist)
      VERSION: 1.20.1
      # https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/
      MOD_PLATFORM: "AUTO_CURSEFORGE"
      # When entering your API Key in a docker compose file you will need to escape any $ character with a second $
      CF_API_KEY: 'CHANGEME'
      CF_PAGE_URL: 'https://www.curseforge.com/minecraft/modpacks/better-beta'
      MODS: |
        https://mediafilez.forgecdn.net/files/5162/837/modmenu-7.2.2.jar
      CF_DOWNLOADS_REPO: '/downloads'
      # Mods can be excluded by passing a comma or space delimited list of project slugs or IDs via CF_EXCLUDE_MODS
      # Exclude erroring Abuseless Hardcore 968038
      CF_EXCLUDE_MODS: '968038'
      # Similarly, there are some mods that are incorrectly tagged as client only
      # For those, pass the project slugs or IDs via CF_FORCE_INCLUDE_MODS.
      #CF_FORCE_INCLUDE_MODS: ''
      # Set to temporarily to "true" to ensure excluded mods are cleaned up.
      #CF_FORCE_SYNCHRONIZE: true
      VIEW_DISTANCE: 24
      MOTD: |
        Welcome to Jam's Better Beta Server!
        
        Better Beta refocuses all progression on exploration and provides quality of life features while providing the classic experience.
      WHITELIST: |
        jamfox
        JobiMollusk
        SergeantRat
        mathiasm99
        Violetic
      OPS: |
        jamfox
      DIFFICULTY: 'hard'
      MAX_PLAYERS: 10
      SPAWN_PROTECTION: 9
      # https://minecraft.wiki/w/Server.properties#level-type
      #LEVEL_TYPE: 'minecraft:default'
      # https://minecraft.wiki/w/Server.properties#generator-settings
      #GENERATOR_SETTINGs:
      SERVER_NAME: 'JamFox Better Beta Server'
      #RCON_PASSWORD: ''
      RCON_PORT: 25575
      # Autopause when last connect was a while ago
      ENABLE_AUTOPAUSE: true
      # pausing causes a single tick to take as long as the process is stopped, so we disable tick watchdog
      MAX_TICK_TIME: -1
      INIT_MEMORY: '1G'
      MAX_MEMORY: '8G'
      TZ: 'Europe/Tallinn'
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /itzg-minecraft/data:/data
      - /itzg-minecraft/downloads:/downloads