---
- name: Is it installed?
  ansible.builtin.stat:
    path: /usr/local/bin/loki
  register: __loki_stat

- name: Get version
  ansible.builtin.command: /usr/local/bin/loki -config.file /etc/loki/loki.yml -version
  changed_when: false
  register: __loki_version_out
  when: __loki_stat.stat.exists

- name: Set version
  ansible.builtin.set_fact:
    __loki_version: "{{ __loki_version_out.stdout_lines[0].split(' ')[2] | replace('v', '') }}"
  when: __loki_stat.stat.exists
