---
- name: Install systemd-unit
  ansible.builtin.template:
    src: "systemd-promtail.j2"
    dest: "/etc/systemd/system/promtail.service"
    mode: '0644'
  notify:
    - Reload systemd promtail
  when: "__loki_go_os == 'linux'"

- name: Configure
  ansible.builtin.import_tasks: promtail-config.yml

- name: Install promtail
  block:
    - name: Download promtail release
      ansible.builtin.get_url:
        url: "{{ __promtail_download }}"
        dest: "/tmp/{{ __promtail_archive }}"
        checksum: "sha256:{{ __loki_download_github }}/v{{ loki_version }}/SHA256SUMS"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2

    - name: Unpack promtail release
      ansible.builtin.unarchive:
        src: "/tmp/{{ __promtail_archive }}"
        dest: "/tmp"
        creates: "/tmp/promtail-{{ __loki_go_os }}-{{ __loki_go_arch }}"
        mode: '0644'
        remote_src: true

    - name: Copy promtail to /usr/local/bin
      ansible.builtin.copy:
        src: "/tmp/promtail-{{ __loki_go_os }}-{{ __loki_go_arch }}"
        dest: "/usr/local/bin/promtail"
        mode: 0755
        owner: root
        group: root
        remote_src: true
      notify: Restart systemd promtail
  check_mode: false
  when:
    - (__promtail_version != loki_version)

- name: Clean-up
  ansible.builtin.file:
    path: "/tmp/{{ item }}"
    state: absent
  when:
    - (__promtail_version != loki_version)
  loop:
    - "{{ __promtail_archive }}"
    - "promtail-{{ __loki_go_os }}-{{ __loki_go_arch }}"
