---
- name: Configure
  ansible.builtin.import_tasks: promtail-config.yml

- name: Download/pre-seed promtail image
  community.docker.docker_image:
    name: "{{ promtail_docker_image }}"
    source: pull

- name: Install systemd service
  ansible.builtin.template:
    src: systemd-promtail-docker.j2
    dest: /etc/systemd/system/promtail.service
    mode: '0644'
  notify:
    - Reload systemd promtail
    - Restart systemd promtail
  when: "__loki_go_os == 'linux'"
