---
- name: Create config directories for promtail
  ansible.builtin.file:
    mode: '0755'
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ promtail_config_directory }}"
    - /var/lib/promtail

- name: Setup configuration
  ansible.builtin.template:
    src: "promtail.yml.j2"
    dest: "/etc/promtail/promtail.yml"
    mode: '0644'
  register: conf_tpl
  notify:
    - Restart systemd promtail
