- name: Create selinux mod for zabbix_server
  ansible.builtin.command:
    cmd: checkmodule -M -m -o /etc/zabbix/my-zabbixserver.mod /etc/zabbix/my-zabbixserver.te
  changed_when: true

- name: Create selinux pp for zabbix_server
  ansible.builtin.command:
    cmd: semodule_package -o /etc/zabbix/my-zabbixserver.pp -m /etc/zabbix/my-zabbixserver.mod
  changed_when: true

- name: Load selinux pp for zabbix_server
  ansible.builtin.command:
    cmd: semodule -i /etc/zabbix/my-zabbixserver.pp
  changed_when: true

- name: Restart zabbix_server
  ansible.builtin.service:
    name: zabbix-server
    state: restarted
