---
- name: Load platform-specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - 'default.yml'
      paths:
        - 'vars'

- name: Install Gitlab Runner (Container)
  ansible.builtin.include_tasks: main-container.yml
  when: gitlab_runner_container_install

- name: Install GitLab Runner (Unix)
  ansible.builtin.include_tasks: main-unix.yml
  when: not gitlab_runner_container_install
