soft_packages_latest: "{{ vars_common_all_soft_apt_tools + vars_common_all_soft_apt_unattended }}"

step_ca_certs_dir: "{{ vars_common_all_certs_path }}"
step_ca_certs_key: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.key"
step_ca_certs_crt: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.crt"
step_ca_certs_jwk_pass: "{{ vars_common_all_step_ca_jwk_password }}"
step_ca_certs_pass_dir: "{{ vars_common_all_certs_path }}"
step_ca_certs:
  - name: "{{ ansible_hostname }}.{{ vars_common_all_default_domain }}"
    crt_path: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.key"
    key_path: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.crt"
    san:
      - "{{ consul_node_role }}.dc1.consul"
      - "{{ nomad_node_role }}.dc1.nomad"
      - "{{ ansible_hostname }}.dc1.nomad"
      - "{{ ansible_hostname }}.dc1.consul"
      - localhost
      - 127.0.0.1

# Consul server
consul_node_role: "server"
consul_group_name: "vb"
consul_datacenter: "dc1"
# Consul install
consul_version: 1.16.2-1
consul_install_from_repo: true
consul_os_repo_prerequisites: false
# Consul config
#consul_iface: "eth0"
consul_user: "consul"
consul_manage_user: true
consul_group: "consul"
consul_manage_group: true
consul_bootstrap_expect: true
#consul_recursors
#consul_iptables_enable
consul_tls_enable: true
consul_tls_ca_crt: "{{ vars_common_all_certs_ca_path }}"
consul_tls_server_crt: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.crt"
consul_tls_server_key: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.key"
consul_tls_files_remote_src: true
consul_encrypt_enable: true
consul_tls_verify_incoming: false # CHANGE ME FOR PROD
consul_tls_verify_outgoing: true
consul_tls_verify_server_hostname: true
auto_encrypt:
  enabled: true
consul_ui: false
consul_raw_key: "{{ vars_common_all_consul_raw_key }}"

# Nomad server
nomad_node_role: "server"
nomad_group_name: "vb"
# Nomad install
nomad_version: 1.6.2
# Nomad config
nomad_user: "nomad"
nomad_manage_user: true
nomad_group: "nomad"
nomad_manage_group: true
nomad_retry_join: true
nomad_encrypt_enable: true
nomad_host_volumes:
  - name: data
    path: /var/data
    owner: root
    group: "{{ nomad_group }}"
    read_only: false
nomad_podman_enable: true
nomad_cni_enable: true
nomad_use_consul: true
nomad_consul_ssl: true
nomad_consul_address: localhost:8500
nomad_consul_ca_file: "{{ consul_tls_dir }}/{{ consul_tls_ca_crt }}"
nomad_consul_cert_file: "{{ consul_tls_dir }}/{{ consul_tls_server_crt }}"
nomad_consul_key_file: "{{ consul_tls_dir }}/{{ consul_tls_server_key }}"
nomad_tls_enable: true
nomad_verify_server_hostname: true
nomad_verify_https_client: false # CHANGE ME FOR PROD
