# Consul server
consul_node_role: "server"
# Consul config
consul_iface: "{{ ansible_default_ipv4.interface }}"
consul_bind_address: "{{ ansible_host }}"

# Nomad server
nomad_node_role: "server"
# Nomad config
nomad_iface: "{{ consul_iface }}"
nomad_bind_address: "{{ consul_bind_address }}"
nomad_advertise_address: "{{ consul_bind_address }}"