---
# role: ansible-role-podman
# file: vars/RedHat.yml

podman_packages:
  - podman
  - podman-compose
  - podman-docker # docker alias for podman
  - systemd-container # for machinectl

podman_manual_mapping: true
