# ATTENTION: PVE needs alternative sources without enterprise license as the default sources require it
- name: Remove PVE enterprise sources
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apt/sources.list.d/pve-enterprise.list
    - /etc/apt/sources.list.d/ceph.list

# Software
# We are using OVS for VLAN bridges
- name: Install extra packages
  ansible.builtin.apt:
    name:
      - openvswitch-switch
    state: latest
