- name: PLAYBOOK FOR GROUP 'VB'
  hosts: vb
  remote_user: jamfox
  become: true
  gather_facts: true
  vars_files:
    - ../vars_common_all.yml
    - ../vars_disabled_roles.yml
    - ../vars_common_hashistack.yml
    #- ../vars_common_nodeexporter.yml

  roles:
    - { role: users_groups,   tags: [all, users_groups],               when: not (disabled_roles.users_groups | default(false))}
    - { role: soft_apt,       tags: [all, soft, soft_apt],             when: not (disabled_roles.soft_apt | default(false)) }
    - { role: motd,           tags: [all, motd],                       when: not (disabled_roles.motd | default(false))}
    - { role: sshd,           tags: [all, sshd],                       when: not (disabled_roles.sshd | default(false))}
    - { role: maxhoesel.smallstep.step_bootstrap_host, tags: [all, step_ca, ca, step_bootstrap_host]}
    - { role: step_ca_certs,  tags: [all, step_ca_certs, step_ca, ca], when: not (disabled_roles.consul | default(false))}
    - { role: consul,         tags: [all, consul],                     when: not (disabled_roles.consul | default(false))}
    - { role: nomad,          tags: [all, nomad],                      when: not (disabled_roles.nomad | default(false))}
    - { role: podman,         tags: [all, podman],                     when: not (disabled_roles.podman | default(false))}
    - { role: nomad_jobs,     tags: [all, nomad_jobs ],                when: not (disabled_roles.nomad_jobs | default(false)) }
    - { role: prometheus.prometheus.node_exporter, tags: [all, exporter, monitor] }
