script_urls: "{{ vars_common_all_script_urls }}"

soft_packages_latest: "{{ vars_common_all_soft_apt_unattended }}"

dnsmasq_domain_local: "{{ vars_common_all_default_domain }}"
dnsmasq_domain: "{{ vars_common_all_default_domain }}"
dnsmasq_base_domain_ip: "{{ vars_common_all_dns_ipv4 }}"
dnsmasq_records:
  - name: "vpn.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi0'].ansible_host }}"
  - name: "octoprint.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "bastion.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "haproxy.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "proxy.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "nas.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "file.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "file.{{ vars_common_all_default_domain }}"
    ip: "{{ vars_common_all_gateway_intra_ipv4 }}"
  - name: "note.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "note.{{ vars_common_all_default_domain }}"
    ip: "{{ vars_common_all_gateway_intra_ipv4 }}"
  - name: "drive.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "drive.{{ vars_common_all_default_domain }}"
    ip: "{{ vars_common_all_gateway_intra_ipv4 }}"
  - name: "sso.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "sso.{{ vars_common_all_default_domain }}"
    ip: "{{ vars_common_all_gateway_intra_ipv4 }}"
  - name: "photo.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "photo.{{ vars_common_all_default_domain }}"
    ip: "{{ vars_common_all_gateway_intra_ipv4 }}"
  - name: "video.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "video.{{ vars_common_all_default_domain }}"
    ip: "{{ vars_common_all_gateway_intra_ipv4 }}"

ddclient_api_login: "{{ vars_common_all_dns_login }}"
ddclient_api_key: "{{ vars_common_all_dns_key }}"
ddclient_api_token: "{{ vars_common_all_dns_token }}"

certbot_domain: "{{ vars_common_all_default_domain }}"
certbot_dns_token: "{{ vars_common_all_dns_token }}"

haproxy_domain: "{{ vars_common_all_default_domain }}"

ipset_countries: "{{ vars_common_all_ipsets_allow }}"
firewall_v4_default_rules:
  001 default policies: "{{ vars_common_all_iptable_default }}"
  002 allow loopback: "{{ vars_common_all_iptable_loopback }}"
  003 allow ping replies: "{{ vars_common_all_iptable_ping }}"
  010 create whitelist chain: "{{ vars_common_all_iptable_whitelist }}"
  011 create locallist chain: "{{ vars_common_all_iptable_locallist }}"
  100 allow established related: "{{ vars_common_all_iptable_established_related }}"
  200 allow ssh: "{{ vars_common_all_iptable_ssh }}"
  400 allow web traffic:
    - -A INPUT -p tcp -m multiport --dport 80,443 -j WHITELIST
  999 drop everything: "{{ vars_common_all_iptable_dropall }}"
