group_vars_green_podman_users:
  - name: 'outside'
    primary_group: 'outside'
    #groups: 
    #  - "kvm" 
    #  - "libvirt" 
    #  - "libvirt-qemu"
    homedir: '/home/outside'
  - name: 'inside'
    primary_group: 'inside'
    #groups: 
    #  - "kvm" 
    #  - "libvirt" 
    #  - "libvirt-qemu"
    homedir: '/home/inside'
users: "{{ vars_common_all_main_users + group_vars_green_podman_users }}"
users_deleted: "{{ vars_common_all_users_deleted }}"

sshd: "{{ vars_common_all_default_sshd }}"

firewalld_enabled: true
firewalld_service_state: started
firewalld_remove_unmanaged: false
firewalld_zones:
  - name: "public"
    short: "Public"
    description: "For use in untrusted public networks. You do not trust the other computers. Only selected incoming connections are accepted."
    interface:
      - name: "enp3s0" # Also needs to be added with network role (check host_vars) or nmcli
    service:
      - name: "ssh"
    port:
      - { port: "51821", protocol: "udp" }
    rule:
      - source: # Needed to route to other hosts in VPN network
          address: "10.7.0.0/24"
        destination: "not address=10.7.0.0/24"
        masquerade: true
  - name: "internal"
    short: "Internal"
    description: "For use on internal networks. You mostly trust the other computers. Only selected incoming connections are accepted."
    interface:
      - name: "wg0" # Also needs to be added via nmcli: nmcli con mod wg0 connection.zone internal
    masquerade: true
    service:
      - name: "ssh"
  - name: "trusted"
    short: "Trusted"
    description: "All network connections in trusted sources are accepted."
    target: "ACCEPT"
    source:
      - address: "10.7.0.0/24"

# For rootless podman to bind to ports lower than 1024, needs net.ipv4.ip_unprivileged_port_start=YOUR_PORT_NUMBER
sysctl_items: "{{ vars_common_all_sysctl_items }}"

selinux_policy: targeted
selinux_state: enforcing

soft_epel_enabled: true
soft_packages_latest: "{{ vars_common_all_admin_packages_rocky }}"
soft_unattended_updates: true

ddclient_install_from_source: true
ddclient_conf_dir: /etc/ddclient
ddclient_api_login: "{{ vars_common_all_dns_login }}"
ddclient_api_key: "{{ vars_common_all_dns_key }}"
ddclient_api_token: "{{ vars_common_all_dns_token }}"

podman_enabled: true
podman_manual_mapping: true
podman_enable_user_socket: true
# Set uid:gid, according to https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md
podman_users:
  inside: '655360:65536'
  outside: '589824:65536'
podman_search_registries: 
  - 'docker.io'
  - 'quay.io'
  - 'registry.access.redhat.com'
  - 'registry.fedoraproject.org'
  - 'registry.redhat.io'
  - 'registry.centos.org'
# Use cgroupfs to support Podman in Podman
podman_configure: true
podman_conf_cgroup_manager: 'cgroupfs'

cron_service_enabled: yes
cron_service_state: started
cron_tasks:
  - name: "Clean unused Podman resources (inside user)"
    user: inside
    weekday: "1"
    hour: "13"
    minute: "0"
    job: "podman image prune -f; podman volume prune -f; podman network prune -f"
  - name: "Clean unused Podman resources (outside user)"
    user: outside
    weekday: "1"
    hour: "13"
    minute: "2"
    job: "podman image prune -f; podman volume prune -f; podman network prune -f"

custom_files:
  - name: "Podman machinectl shortcut"
    blockinfile:
      - "#!/bin/bash"
      - ""
      - "if [ \"$(whoami)\" != \"jamfox\" ]; then"
      - "    echo \"This script can only be run by user jamfox\""
      - "    exit 1"
      - "fi"
      - ""
      - "if [ \"$1\" != \"inside\" ] && [ \"$1\" != \"outside\" ]; then"
      - "    echo \"Usage: $0 {inside|outside}\""
      - "    exit 1"
      - "fi"
      - ""
      - "MACHINE=$1"
      - "sudo machinectl shell \"${MACHINE}@\" /bin/bash"
    dest: "/usr/local/bin/jsh"
    mode: "0750"
    owner: "jamfox"
    group: "admin"

certbot_domain: "{{ vars_common_all_default_domain }}"
certbot_dns_token: "{{ vars_common_all_dns_token }}"

haproxy_domain: "{{ vars_common_all_default_domain }}"