script_urls: "{{ vars_common_all_script_urls }}"

soft_packages_latest: "{{ vars_common_all_soft_apt_unattended }}"

ipset_countries: "{{ vars_common_all_ipsets_allow }}"
firewall_v4_default_rules:
  001 default policies: "{{ vars_common_all_iptable_default }}"
  002 allow loopback: "{{ vars_common_all_iptable_loopback }}"
  003 allow ping replies: "{{ vars_common_all_iptable_ping }}"
  010 create whitelist chain: "{{ vars_common_all_iptable_whitelist }}"
  100 allow established related: "{{ vars_common_all_iptable_established_related }}"
  200 allow ssh: "{{ vars_common_all_iptable_ssh }}"
  400 allow web traffic:
    - -A INPUT -p tcp -m multiport --dport 80,443 -j WHITELIST
  999 drop everything: "{{ vars_common_all_iptable_dropall }}"
