- name: Install snapd
  ansible.builtin.apt:
    name:
      - snapd
    state: latest

- name: Install snap core
  community.general.snap:
    name:
      - core

- name: Remove system default certbot
  ansible.builtin.apt:
    name:
      - certbot
    state: absent

- name: Install cerbot with option --classic
  community.general.snap:
    name: certbot
    classic: true
    options:
      - trust-plugin-with-root=ok

- name: Install cerbot-cloudflare
  community.general.snap:
    name: certbot-dns-cloudflare

- name: Link certbot to /usr/bin
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Set cloudflare certbot credentials
  ansible.builtin.copy:
    dest: /root/.certbot.ini
    mode: "0600"
    content: |
      dns_cloudflare_api_token = {{ certbot_dns_token }}

- name: Check if cert exists
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ certbot_domain }}/"
  register: r_letsencrypt_live

- name: Get letsencrypt cert
  ansible.builtin.shell: certbot certonly --non-interactive --agree-tos -m acme@{{ certbot_domain }} --dns-cloudflare --dns-cloudflare-credentials /root/.certbot.ini -d {{ certbot_domain }},*.{{ certbot_domain }} --preferred-challenges dns-01
  when: not r_letsencrypt_live.stat.exists
