{
 "title": "JamLab Nomad Cluster Overview",
 "description": "Nomad cluster dashboard. Using built in nomad's exporter and loki. Example cluster is present there https://github.com/theztd/startup-infra-docker in ",
 "tags": [
  "nomad",
  "host",
  "cluster"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "datacenter",
    "label": "DC",
    "query": {
     "query": "label_values(nomad_client_uptime, datacenter)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(nomad_client_uptime{datacenter=~\"$datacenter\"}, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_job_status_running{}",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Allocated CPU  ($datacenter)",
   "type": "piechart",
   "description": "In the whole cluster",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_client_allocs_cpu_allocated) by (exported_job)",
     "legendFormat": "{{exported_job}}"
    },
    {
     "expr": "sum(nomad_client_unallocated_cpu)",
     "legendFormat": "Free cluster CPU"
    }
   ]
  },
  {
   "title": "OOM kills",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "nomad_client_allocs_oom_killed{}",
     "legendFormat": "oom"
    },
    {
     "expr": "timestamp(nomad_client_allocs_oom_killed{}) * 1000 - 3600000",
     "legendFormat": "from"
    },
    {
     "expr": "timestamp(nomad_client_allocs_oom_killed{}) * 1000 + 3600000",
     "legendFormat": "to"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"nomad\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nomad_nomad_job_status_pending", "legendFormat": "Pending" }
   ]
  },
  {
   "title": "Allocations",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_complete{}",
     "legendFormat": "complete"
    },
    {
     "expr": "nomad_nomad_job_summary_failed{}",
     "legendFormat": "failed"
    },
    { "expr": "nomad_nomad_job_summary_lost{}", "legendFormat": "lost" },
    {
     "expr": "nomad_nomad_job_summary_starting{env=\"$env\"}",
     "legendFormat": "starting"
    },
    {
     "expr": "nomad_nomad_job_summary_queued{env=\"$env\"}",
     "legendFormat": "queued"
    },
    {
     "expr": "nomad_nomad_job_summary_running{env=\"$env\"}",
     "legendFormat": "running"
    }
   ]
  },
  {
   "title": "Allocated MEM ($datacenter)",
   "type": "piechart",
   "description": "In whole cluster",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_client_allocs_memory_allocated) by (exported_job)",
     "legendFormat": "{{exported_job}}"
    },
    {
     "expr": "sum(nomad_client_host_memory_free)",
     "legendFormat": "Free cluster MEM"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nomad_nomad_job_status_dead", "legendFormat": "Dead" }
   ]
  },
  {
   "title": "Node Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Allocation status",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 14 },
   "repeat": "host",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_allocations_migrating{datacenter=~\"$datacenter\", host=~\"$host\"}",
     "legendFormat": "Migrating"
    },
    {
     "expr": "nomad_client_allocations_blocked{datacenter=~\"$datacenter\", host=~\"$host\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "nomad_client_allocations_pending{datacenter=~\"$datacenter\", host=~\"$host\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "nomad_client_allocations_running{datacenter=~\"$datacenter\", host=~\"$host\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "nomad_client_allocations_terminal{datacenter=~\"$datacenter\", host=~\"$host\"}",
     "legendFormat": "Terminal"
    }
   ]
  },
  {
   "title": "Free Disk Space ($host)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 14 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nomad_client_host_disk_available{datacenter=~\"$datacenter\", host=~\"$host\"}) by (disk) / max(nomad_client_host_disk_size{datacenter=~\"$datacenter\", host=~\"$host\"}) by (disk) ",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 10, "y": 14 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_uptime{datacenter=~\"$datacenter\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Free memmory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 17 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_host_memory_free{datacenter=~\"$datacenter\", host=~\"$host\"} /nomad_client_host_memory_total{datacenter=~\"$datacenter\", host=~\"$host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nomad Logs ($datacenter)",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "{application=\"nomad\"} |= ``"
      }
     ]
    },
    {
     "title": "Podman (Nomad service nodes only) Logs ($datacenter)",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "{application=\"podman\", hostname=~\"vs[0-9]\"} |= ``"
      }
     ]
    }
   ]
  },
  { "title": "RAFT status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Raft Commit Time",
   "type": "timeseries",
   "description": "Time difference between when a message was first passed into Raft and when the resulting commit took place on the leader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_raft_commitTime{quantile=\"0.9\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Raft Apply Count",
   "type": "timeseries",
   "description": "Number of Raft transactions - general indicator of the write load on the servers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nomad_raft_apply{}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}