custom_scripts: "{{ vars_common_all_scripts_admin }}"

soft_packages_latest: "{{ vars_common_all_soft_apt_tools + vars_common_all_soft_apt_unattended }}"

users: "{{ vars_common_all_main_users }}"

sshd: "{{ vars_common_all_default_sshd }}"

ipset_countries: "{{ vars_common_all_ipsets_allow }}"
firewall_v4_default_rules:
  001 default policies: "{{ vars_common_all_iptable_default }}"
  002 allow loopback: "{{ vars_common_all_iptable_loopback }}"
  003 allow ping replies: "{{ vars_common_all_iptable_ping }}"
  010 create whitelist chain: "{{ vars_common_all_iptable_whitelist }}"
  011 create locallist chain: "{{ vars_common_all_iptable_locallist }}"
  100 allow established related: "{{ vars_common_all_iptable_established_related }}"
  200 allow ssh: "{{ vars_common_all_iptable_ssh }}"
  300 allow wireguard:
    - -t nat -I POSTROUTING -j MASQUERADE -o eth0
    - -I INPUT 1 -i wg0 -j ACCEPT
    - -I FORWARD 1 -i eth0 -o wg0 -j ACCEPT
    - -I FORWARD 1 -i wg0 -o eth0 -j ACCEPT
    - -I INPUT 1 -i eth0 -p udp --dport 51820 -j WHITELIST
  500 allow dns:
    - -A INPUT -p udp --dport 53 -s 192.168.0.0/16 -j LOCALLIST
    - -A INPUT -p tcp --dport 53 -s 192.168.0.0/16 -j LOCALLIST
  600 allow octoprint: 
    - -A INPUT -p tcp -m multiport --dport 80,443,8080 -j LOCALLIST
    - -A INPUT -p tcp -m multiport --dport 443 -s 149.154.160.0/20 -j ACCEPT # https://core.telegram.org/bots/webhooks
    - -A INPUT -p tcp -m multiport --dport 443 -s 91.108.4.0/22 -j ACCEPT # https://core.telegram.org/bots/webhooks
  999 drop everything: "{{ vars_common_all_iptable_dropall }}"

dnsmasq_domain_local: "{{ vars_common_all_default_domain }}"
dnsmasq_domain: "{{ vars_common_all_default_domain }}"
dnsmasq_base_domain_ip: "{{ vars_common_all_dns_ipv4 }}"
dnsmasq_records:
  - name: "vpn.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi0'].ansible_host }}"
  - name: "octoprint.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "bastion.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "haproxy.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "proxy.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "nas.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "file.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "note.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "drive.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "sso.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "photo.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"
  - name: "video.{{ vars_common_all_default_domain }}"
    ip: "{{ hostvars['rpi1'].ansible_host }}"