- name: PLAYBOOK FOR HOST 'PORTAINER'
  hosts: portainer
  remote_user: jamfox
  become: true
  vars_files:
    - ../vars_common_all.yml
    - ../vars_disabled_roles.yml
    - ../vars_common_promtail.yml
    - ../vars_common_rsyslog_client.yml
    - ../vars_common_nodeexporter.yml

  roles:
    - { role: users_groups,   tags: [all, users_groups],   when: not (disabled_roles.users_groups | default(false))}
    - { role: custom_scripts, tags: [all, custom_scripts], when: not (disabled_roles.custom_scripts | default(false))}
    - { role: soft_apt,       tags: [all, soft, soft_apt], when: not (disabled_roles.soft_apt | default(false)) }
    - { role: pip,            tags: [all, soft, pip] }
    - { role: motd,           tags: [all, motd],           when: not (disabled_roles.motd | default(false))}
    - { role: sshd,           tags: [all, sshd],           when: not (disabled_roles.sshd | default(false))}
    - { role: rsyslog,        tags: [all, rsyslog],        when: not (disabled_roles.rsyslog | default(false)) }
    - { role: prometheus.prometheus.node_exporter, tags: [all, exporter, monitor] }
    - { role: loki_promtail, tags: [all, loki_promtail, monitor] }
    - { role: docker,        tags: [all, docker] }
    # Portainer installed manually
    - { role: maxhoesel.smallstep.step_bootstrap_host, tags: [all, step_ca, ca, step_bootstrap_host]}
    - { role: step_ca_certs,  tags: [all, step_ca_certs, step_ca, ca], when: not (disabled_roles.step_ca_certs | default(false))}