---
# Unix
- name: Restart_gitlab_runner
  ansible.builtin.service: name=gitlab-runner state={{ gitlab_runner_restart_state }}
  become: true
  when: not gitlab_runner_container_install

# Container
- name: Restart_gitlab_runner_container
  community.docker.docker_container:
    name: "{{ gitlab_runner_container_name }}"
    restart: true
  when: gitlab_runner_container_install
