---
# File: tasks/tls.yml - TLS tasks for Vault

- name: Create TLS directory
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0750
  with_items:
    - "{{ vault_tls_certs_path }}"
    - "{{ vault_tls_private_path }}"
  when: vault_tls_copy_keys | bool
  tags:
    - tls

- name: Vault SSL Certificate and Key
  become: true
  ansible.builtin.copy:
    remote_src: "{{ vault_tls_files_remote_src }}"
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "{{ vault_tls_ca_file }}"
      dest: "{{ vault_tls_certs_path }}/{{ vault_tls_ca_file | basename }}"
      mode: "0644"
    - src: "{{ vault_tls_cert_file }}"
      dest: "{{ vault_tls_certs_path }}/{{ vault_tls_cert_file | basename }}"
      mode: "0644"
    - src: "{{ vault_tls_key_file }}"
      dest: "{{ vault_tls_private_path }}/{{ vault_tls_key_file | basename }}"
      mode: "0600"
  when: vault_tls_copy_keys | bool
  notify:
    - Restart vault
    - Reload vault
  tags:
    - tls
