- name: Install chrony if CentOS/RedHat
  ansible.builtin.yum:
    name: "{{ chrony_packages }}"
    state: "{{ chrony_package_state | default(default_package_state | default('present')) }}"
  when: ansible_os_family in ['CentOS', 'RedHat']

- name: Install chrony if Debian
  ansible.builtin.apt:
    name: "{{ chrony_packages }}"
    state: "{{ chrony_package_state | default(default_package_state | default('present')) }}"
  when: ansible_os_family == "Debian"

- name: Copy chrony config
  ansible.builtin.template:
    dest: /etc/
    src: files/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart chronyd service

- name: Enable and start chronyd
  ansible.builtin.systemd:
    name: chronyd
    enabled: true
    state: started

- name: Makestep chrony, sync time if first run
  ansible.builtin.command:
    cmd: chronyc -a makestep
  when: chrony_first_run
