- name: PLAYBOOK FOR HOST 'PVE'
  hosts: pve
  become: true
  vars_files:
    - ../vars_common_all.yml
    - ../vars_disabled_roles.yml

  roles:
    - { role: proxmox,        tags: [all, proxmox],        when: not (disabled_roles.proxmox | default(false))}
    - { role: soft_apt,       tags: [all, soft, soft_apt], when: not (disabled_roles.soft_apt | default(false)) }
    - { role: motd,           tags: [all, motd],           when: not (disabled_roles.motd | default(false))}
    - { role: sshd,           tags: [all, sshd],           when: not (disabled_roles.sshd | default(false))}
