# Default values, override in host or host group variables
firewalld_packages:
  - nftables
  - firewalld

# service enabled on boot
firewalld_enabled: true

# service run state (started, stopped, restarted)
firewalld_service_state: started

# restart service on configuration change
firewalld_service_restart_on_change: true

# firewalld configuration
firewalld_config: {}

# firewall rules
# see https://docs.ansible.com/ansible/latest/modules/firewalld_module.html
# example:
#  firewalld_rules:
#    - service: http
#      permanent: true
#      state: enabled
#    - rich_rule: rule family={{ item }} forward-port port=443 protocol=tcp to-port=8443
#      zone:      public
#      permanent: true
#      immediate: true
#      state:     enabled
firewalld_rules: []

# Configure permanent firewalld ipsets (xml config file)
firewalld_ipsets: []
# Configure permanent firewalld services (xml config file)
firewalld_services: []
# Configure permanent firewalld zones (xml config file)
firewalld_zones: []
# Remove unmanaged ipsets, services and zones
firewalld_remove_unmanaged: true

# firewalld configuration defaults
firewalld_config_defaults:
  DefaultZone: public
  CleanupOnExit: true
  Lockdown: true
  IPv6_rpfilter: true
  IndividualCalls: false
  LogDenied: "off"
  FirewallBackend: nftables
  FlushAllOnReload: true
  RFC3964_IPv4: true
  AllowZoneDrifting: false
