- name: Disable systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped

- name: Install dnsmasq
  ansible.builtin.apt:
    name:
      - dnsmasq
    state: latest

- name: Template dnsmasq configs
  ansible.builtin.template:
    src: "files/{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - { src: jamlab-dns.conf.j2, dest: /etc/dnsmasq.d/jamlab-dns.conf }
  - { src: hosts.jamfox.dev.j2, dest: /etc/hosts.jamfox.dev }
  notify: Restart dnsmasq
