- name: Install Zabbix for CentOS/RedHat
  when: ansible_os_family in ['CentOS', 'RedHat']
  block:
    - name: Add Zabbix repo
      ansible.builtin.yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        state: present
    - name: Install Zabbix agent
      ansible.builtin.yum:
        name: "{{ zabbix_agent_packages }}"
        state: "{{ zabbix_package_state | default(default_package_state | default('present')) }}"

- name: Install Zabbix for Debian
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
  when: ansible_os_family == "Debian"

- name: Zabbix agent server in conf
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^Server="
    line: Server=10.10.100.250

- name: Zabbix agent user-defined items
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.d/userparameter_md.conf
    line: UserParameter=hpc2custom.kernel.perf_event_max_sample_rate,sysctl -n kernel.perf_event_max_sample_rate
    create: true
    mode: "0644"

- name: Enable and start Zabbix agent service
  ansible.builtin.systemd:
    name: zabbix-agent
    state: started
    enabled: true
