# This block is run instead of running tasks in this main file
# to follow results of item tasks in a readable manner
- name: Custom files loop
  ansible.builtin.include_tasks: "file.yml"
  loop: "{{ custom_files }}"
  loop_control:
    loop_var: custom_file
  when: custom_file.dest is defined

- name: Copy custom directories
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default(omit) }}"
    force: "{{ item.force | default('false') }}"
  with_items: "{{ custom_directories }}"
  when: item.src is defined
