---
- name: Reload systemd loki
  ansible.builtin.systemd:
    name: "loki"
    daemon_reload: true
    enabled: true

- name: Restart systemd loki
  ansible.builtin.service:
    name: "loki"
    state: restarted

- name: Reload systemd promtail
  ansible.builtin.systemd:
    name: "promtail"
    daemon_reload: true
    enabled: true

- name: Restart systemd promtail
  ansible.builtin.service:
    name: "promtail"
    state: restarted
