vars_common_all_default_domain: "jamfox.dev"
vars_common_all_default_netblock: "192.168.0.0/16"
vars_common_all_gateway_ipv4: "192.168.10.1"
vars_common_all_gateway_intra_ipv4: "192.168.1.190"
vars_common_all_loki_ipv4: "192.168.10.50"
vars_common_all_mask_ipv4: "/24"
vars_common_all_proxy_ipv4: "192.168.10.80"
vars_common_all_dns_ipv4: "192.168.10.53"
vars_common_all_dns_default_port: "53"
vars_common_all_pve_default_ipv4: "192.168.10.100"
vars_common_all_pve_default_port: "8006"

var_common_all_consul_dns_port: "8600"

hostname: "{{ ansible_hostname }}.{{ vars_common_all_default_domain }}"
nameservers:
  - "{{ vars_common_all_dns_ipv4 }}"
searchdomain: "{{ vars_common_all_default_domain }}"

# Scripts
vars_common_all_scripts_admin:
  - name: "ansible-parallel"
    url: "https://raw.githubusercontent.com/JamFox/ansible-parallel/main/ansible-parallel"
    dest: "/usr/local/bin/"
    mode: "0774"
    owner: "{{ vars_common_all_main_user }}"
    group: "{{ vars_common_all_main_group }}"
  - name: "teams-msg"
    url: "https://raw.githubusercontent.com/JamFox/ansible-parallel/main/teams-msg"
    mode: "0774"
    owner: "{{ vars_common_all_main_user }}"
    group: "{{ vars_common_all_main_group }}"
  - name: "telegram-msg"
    url: "https://raw.githubusercontent.com/JamFox/ansible-parallel/main/telegram-msg"
    mode: "0774"
    owner: "{{ vars_common_all_main_user }}"
    group: "{{ vars_common_all_main_group }}"
  - name: ".bashrc"
    url: "https://raw.githubusercontent.com/JamFox/dotfiles/main/.bashrc"
    dest: "/home/jamfox/"
    mode: "0640"
    owner: "{{ vars_common_all_main_user }}"
    group: "{{ vars_common_all_main_group }}"
vars_common_all_scripts_vault_client:
  - name: "vault-login"
    link: "/usr/local/bin/vl"
    local: "files/vault-login.sh"
    dest: "/usr/local/bin"
    mode: "0755"
    owner: "{{ vars_common_all_main_user }}"
    group: "{{ vars_common_all_main_group }}"
  - name: "vault-ssh"
    link: "/usr/local/bin/vssh"
    local: "files/vault-ssh.sh"
    dest: "/usr/local/bin"
    mode: "0755"
    owner: "{{ vars_common_all_main_user }}"
    group: "{{ vars_common_all_main_group }}"

vars_common_all_ipsets_allow:
  - "at"
  - "be"
  - "bg"
  - "hr"
  - "cy"
  - "ch"
  - "cz"
  - "dk"
  - "ee"
  - "fi"
  - "fr"
  - "de"
  - "gr"
  - "hu"
  - "ie"
  - "it"
  - "lv"
  - "lt"
  - "lu"
  - "mt"
  - "no"
  - "nl"
  - "pl"
  - "pt"
  - "ro"
  - "sk"
  - "si"
  - "es"
  - "se"
  - "gb"

vars_common_all_iptable_default:
  - -P INPUT ACCEPT
  - -P OUTPUT ACCEPT
  - -P FORWARD DROP
vars_common_all_iptable_loopback:
  - -A INPUT -i lo -s 127.0.0.0/8 -d 127.0.0.0/8 -j ACCEPT
vars_common_all_iptable_ping:
  - -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
  - -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT
vars_common_all_iptable_locallist:
  - -N LOCALLIST
  - -A LOCALLIST -s 127.0.0.0/8 -j ACCEPT
  - -A LOCALLIST -s 192.168.0.0/16 -j ACCEPT
  - -A LOCALLIST -s 172.16.0.0/12 -j ACCEPT
  - -A LOCALLIST -s 10.0.0.0/8 -j ACCEPT
  - -A LOCALLIST -j DROP
vars_common_all_iptable_whitelist:
  - -N WHITELIST
  - -A WHITELIST -s 127.0.0.0/8 -j ACCEPT
  - -A WHITELIST -s 192.168.0.0/16 -j ACCEPT
  - -A WHITELIST -s 172.16.0.0/12 -j ACCEPT
  - -A WHITELIST -s 10.0.0.0/8 -j ACCEPT
  - -A WHITELIST -m set --set at src -j ACCEPT
  - -A WHITELIST -m set --set be src -j ACCEPT
  - -A WHITELIST -m set --set bg src -j ACCEPT
  - -A WHITELIST -m set --set hr src -j ACCEPT
  - -A WHITELIST -m set --set cy src -j ACCEPT
  - -A WHITELIST -m set --set ch src -j ACCEPT
  - -A WHITELIST -m set --set cz src -j ACCEPT
  - -A WHITELIST -m set --set dk src -j ACCEPT
  - -A WHITELIST -m set --set ee src -j ACCEPT
  - -A WHITELIST -m set --set fi src -j ACCEPT
  - -A WHITELIST -m set --set fr src -j ACCEPT
  - -A WHITELIST -m set --set de src -j ACCEPT
  - -A WHITELIST -m set --set gr src -j ACCEPT
  - -A WHITELIST -m set --set hu src -j ACCEPT
  - -A WHITELIST -m set --set ie src -j ACCEPT
  - -A WHITELIST -m set --set it src -j ACCEPT
  - -A WHITELIST -m set --set lv src -j ACCEPT
  - -A WHITELIST -m set --set lt src -j ACCEPT
  - -A WHITELIST -m set --set lu src -j ACCEPT
  - -A WHITELIST -m set --set mt src -j ACCEPT
  - -A WHITELIST -m set --set no src -j ACCEPT
  - -A WHITELIST -m set --set nl src -j ACCEPT
  - -A WHITELIST -m set --set pl src -j ACCEPT
  - -A WHITELIST -m set --set pt src -j ACCEPT
  - -A WHITELIST -m set --set ro src -j ACCEPT
  - -A WHITELIST -m set --set sk src -j ACCEPT
  - -A WHITELIST -m set --set si src -j ACCEPT
  - -A WHITELIST -m set --set es src -j ACCEPT
  - -A WHITELIST -m set --set se src -j ACCEPT
  - -A WHITELIST -m set --set gb src -j ACCEPT
  - -A WHITELIST -j DROP
vars_common_all_iptable_established_related:
  - -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
vars_common_all_iptable_ssh:
  - -A INPUT -p tcp --dport ssh -s 127.0.0.0/8 -j ACCEPT
  - -A INPUT -p tcp --dport ssh -s 192.168.0.0/16 -j ACCEPT
  - -A INPUT -p tcp --dport 22 -j DROP
vars_common_all_iptable_dropall:
  - -P INPUT DROP

vars_common_all_soft_apt_tools:
  - vim
  - jq
  - curl
  - wget
  - vim
  - git
  - keychain
  - tmux
  - python3
  - net-tools
  - dnsutils
  - build-essential
  - procps
  - file
  - gpg
  - ansible
  - ansible-lint

vars_common_all_soft_apt_unattended:
  - unattended-upgrades
  - apt-listchanges

vars_common_all_soft_apt_hashicorp:
  - packer
  - terraform
  - consul
  - vault

pip_package: python3-pip
pip_executable: "{{ 'pip3' if pip_package.startswith('python3') else 'pip' }}"

vars_common_all_users_deleted:
  - name: "rocky"
  - name: "debian"
  - name: "ubuntu"
  - name: "ali"
vars_common_all_main_user: jamfox
vars_common_all_main_group: admin
vars_common_all_main_users:
  - name: "{{ vars_common_all_main_user }}"
    primary_group: "{{ vars_common_all_main_group }}"
    homedir: "/home/{{ vars_common_all_main_user }}"
    sudo: "%{{ vars_common_all_main_group }} ALL=(ALL) NOPASSWD: ALL"
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILayJ7ZP6Z6IDms4ujnz9nRnAJEIXwyto1SbSwfzjqst jamfox"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM0ULeAHpFD9I+oIBImBw+UHQui4Q8V1jQThOIlYExi5 jamfox@5t"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICMfvfGWOQuhmQ1MRJifS0VddwvwUpFYiETPb1V5W+5Y katurv@hpcbook"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJruHSfE0z4yEY4SJW5/ZnBjgpvlz8u199+s4srW85WV jamfox@DESKTOP-6KK4JTC"

vars_common_all_default_sshd:
  LogLevel: "INFO"
  PasswordAuthentication: "no"
  PermitRootLogin: "prohibit-password"
  AllowAgentForwarding: "yes"
  ChallengeResponseAuthentication: "no"
  GSSAPIAuthentication: "no"
  KerberosAuthentication: "no"
  UseDNS: "no"
  GSSAPICleanupCredentials: "yes"
  UsePAM: "yes"
  X11Forwarding: "yes"
  PrintMotd: "no"
  AcceptEnv: "LANG LC_*"
  Subsystem: "sftp /usr/lib/openssh/sftp-server"

vars_common_all_dns_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61373238313934323533663766663730643564616662353333323662616665383739663264633364
  6333393262643662663532653264633764666332336638380a633231313937383637326262306230
  62306138356263663338633431316663656464386663633539323136643131313139633638326331
  6664656130666537650a313066333835666366363963346636643362616466363831336263663966
  36626436373631343336366233633235393532636432323337626438653962333266616262353762
  3165316264646331623333363338643133343135316561633531

vars_common_all_sysctl_items:
  - name: net.ipv6.conf.all.disable_ipv6
    value: "1"
    file: 98-disable_ipv6.conf
  - name: net.ipv6.conf.default.disable_ipv6
    value: "1"
    file: 98-disable_ipv6.conf
  - name: net.ipv6.conf.lo.disable_ipv6
    value: "1"
    file: 98-disable_ipv6.conf

vars_common_all_admin_packages_rocky:
  - bind-utils
  - telnet
  - tcpdump
  - tar
  - unzip
  - vim
  - wget
  - htop