soft_packages_latest: "{{ vars_common_all_soft_apt_tools + vars_common_all_soft_apt_unattended }}"
soft_packages_keep_latest_exclude:
  - vault
  - nomad
  - consul
  - systemd-container # machinectl

podman_system_users:
  - name: "podman"
    primary_group: "podman"
    groups:
      - "{{ nomad_group }}"
      - systemd-journal
    homedir: "/home/podman"
  - name: "{{ nomad_user }}"
    primary_group: "{{ nomad_group }}"
    groups:
      - systemd-journal
    comment: "Nomad user"
    system: true
podman_enabled: true
podman_manual_mapping: true
podman_enable_user_socket: true
# Set uid:gid, according to https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md
podman_users:
  podman: "231072:65537"
  nomad: "296609:65537"
podman_registries:
  - "docker.io"
  - "quay.io"
users: "{{ vars_common_all_main_users + podman_system_users + vars_common_all_temp_hashistack_users }}"

sshd: "{{ vars_common_all_default_sshd }}"

step_ca_certs_dir: "{{ vars_common_all_certs_path }}"
step_ca_certs_key: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.key"
step_ca_certs_crt: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.crt"
step_ca_certs_jwk_pass: "{{ vars_common_all_step_ca_jwk_password }}"
step_ca_certs_pass_dir: "{{ vars_common_all_certs_path }}"
step_ca_certs:
  - name: "{{ ansible_hostname }}.{{ vars_common_all_default_domain }}"
    crt_path: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.crt"
    key_path: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.key"
    not_after: 720h
    renew_after: 20h
    san:
      - "{{ consul_node_role }}.{{ consul_datacenter }}.consul"
      - "{{ ansible_hostname }}.{{ consul_datacenter }}.consul"
      - "{{ nomad_node_role }}.{{ consul_datacenter }}.nomad"
      - "{{ ansible_hostname }}.{{ consul_datacenter }}.nomad"
      - "{{ nomad_node_role }}.global.nomad"
      - localhost
      - 127.0.0.1
      - "{{ ansible_host }}"
#step_ca_certs_renew:
#    crt_path: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.crt"
#    key_path: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.key"
#    renew_after: 20h

# Consul general
consul_group_name: "vb"
consul_servers: "{{ groups['vb'] }}"
consul_bootstrap_expect_value: "{{ groups['vb'] | length }}"
consul_datacenter: "dc1"
# Consul install
consul_version: 1.17.1-1
consul_install_from_repo: true
consul_os_repo_prerequisites: false
# Consul config
consul_user: "consul"
consul_manage_user: true
consul_group: "hashistack"
consul_manage_group: true
consul_raft_protocol: 3
consul_bootstrap_expect: true
#consul_recursors
#consul_iptables_enable
consul_ports_http: 8500
consul_ports_https: 8501
consul_ports_grpc_tls: 8502
consul_addresses_https: "0.0.0.0"
consul_addresses_dns: "0.0.0.0"
consul_tls_enable: true
consul_tls_dir: "/etc/hashistack_consul"
consul_tls_ca_crt: "{{ vars_common_all_certs_ca_path }}"
consul_tls_server_crt: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.crt"
consul_tls_server_key: "{{ vars_common_all_certs_path }}/{{ vars_common_all_certs_name }}.key"
consul_tls_files_remote_src: true
consul_encrypt_enable: true
# Allow clients to not present their own cert
consul_tls_verify_incoming: false
consul_tls_verify_incoming_https: false
# Still require it on RPC
consul_tls_verify_incoming_rpc: true
consul_tls_verify_outgoing: true
consul_tls_verify_server_hostname: true
#auto_encrypt:
#  enabled: true
consul_ui: false
consul_raw_key: "{{ vars_common_all_consul_raw_key }}"
consul_syslog_enable: true
consul_log_level: INFO
consul_autopilot_enable: true
consul_autopilot_cleanup_dead_Servers: true
consul_connect_enabled: true
# Custom
consul_config_custom:
  telemetry:
    disable_hostname: true
    enable_host_metrics: true
    prometheus_retention_time: "4h"

# Nomad general
nomad_group_name: "hashistack"
nomad_datacenter: "{{ consul_datacenter }}"
nomad_bootstrap_expect: "{{ consul_bootstrap_expect_value }}"
nomad_no_host_uuid: true
# Nomad install
nomad_version: 1.7.3
# Nomad config
nomad_user: "nomad"
nomad_manage_user: true
nomad_group: "{{ consul_group }}"
nomad_manage_group: true
nomad_retry_join: true
nomad_encrypt_enable: true
nomad_host_volumes:
  - name: data
    path: /var/data
    owner: root
    group: "{{ nomad_group }}"
    read_only: false
nomad_raft_protocol: 3
nomad_docker_enable: false
nomad_podman_enable: true
nomad_cni_enable: true
nomad_use_consul: true
nomad_consul_ssl: true
nomad_consul_address: localhost:8501
nomad_tls_dir: "/etc/hashistack_nomad"
nomad_ca_file: "{{ consul_tls_ca_crt }}"
nomad_cert_file: "{{ consul_tls_server_crt }}"
nomad_key_file: "{{ consul_tls_server_key }}"
nomad_consul_ca_file: "{{ nomad_tls_dir }}/{{ nomad_ca_file | basename }}"
nomad_consul_cert_file: "{{ nomad_tls_dir }}/{{ nomad_cert_file | basename }}"
nomad_consul_key_file: "{{ nomad_tls_dir }}/{{ nomad_key_file | basename }}"
nomad_consul_tags: "nomad"
nomad_tls_copy_keys: true
nomad_tls_files_remote_src: true
nomad_tls_enable: true
nomad_verify_server_hostname: true
# Allow clients to not present their own cert
nomad_verify_https_client: false
nomad_syslog_enable: true
nomad_log_level: INFO
nomad_autopilot: true
nomad_autopilot_cleanup_dead_servers: true
# Nomad Telemetry
nomad_telemetry: true
nomad_telemetry_prometheus_metrics: true
nomad_telemetry_disable_hostname: true
nomad_telemetry_publish_allocation_metrics: true
nomad_telemetry_publish_node_metrics: true
nomad_telemetry_collection_interval: "5s"

nomad_jobs_user: "{{ nomad_user }}"
nomad_jobs_group: "{{ nomad_group }}"

nomad_jobs_nomad_config_dir: "{{ nomad_tls_dir }}"
nomad_jobs_nomad_cert_file: "{{ nomad_cert_file | basename }}"
nomad_jobs_nomad_key_file: "{{ nomad_key_file | basename }}"
nomad_jobs_nomad_ca_file: "{{ nomad_ca_file | basename }}"

nomad_jobs_consul_addr: "https://127.0.0.1:{{ consul_ports_https }}"
nomad_jobs_consul_api_endpoint: "v1"

# Custom
nomad_allow_purge_config: true
#nomad_config_custom:
#    log_file: "/var/log/nomad/nomad.log"
#  log_json: true
