soft_packages_latest: "{{ vars_common_all_soft_apt_tools + vars_common_all_soft_apt_unattended }}"

# Consul client
consul_node_role: "client"
# Consul config
consul_iface: "{{ ansible_default_ipv4.interface }}"
consul_bind_address: "{{ ansible_host }}"
consul_addresses_dns: "{{ ansible_host }}"
consul_addresses_http: 127.0.0.1

# Nomad client
nomad_node_role: "client"
# Nomad config
nomad_iface: "{{ consul_iface }}"
nomad_bind_address: "{{ consul_bind_address }}"
nomad_advertise_address: "{{ consul_bind_address }}"
