soft_extra_repos:
  - repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
  - repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
  - repo: "deb http://download.proxmox.com/debian/ceph-quincy {{ ansible_distribution_release }} no-subscription"

soft_extra_sources:
  - { url: https://apt.releases.hashicorp.com/gpg }

soft_packages_latest_pve:
  - sudo
soft_packages_latest: "{{ vars_common_all_soft_apt_unattended + vars_common_all_soft_apt_tools + vars_common_all_soft_apt_hashicorp + soft_packages_latest_pve }}"

sshd: "{{ vars_common_all_default_sshd }}"

users: "{{ vars_common_all_main_users }}"
users_deleted: "{{ vars_common_all_users_deleted }}"

provision_vm_default_target_node: "{{ groups['pve'][0] }}"
provision_vm_gateway: "{{ vars_common_all_gateway_ipv4 }}"
provision_vm_cidr: "{{ vars_common_all_mask_ipv4 }}"
provision_vm_nameserver: "{{ vars_common_all_gateway_ipv4 }}"
provision_vm_searchdomain: "{{ vars_common_all_default_domain }}"

# Rework into more reusable
provision_vm1_hostgroup: "vm_svc"
provision_vm2_hostgroup: "vm_base"
provision_vm3_hostgroup: "vm_test"
provision_vm1_prefix: "{{ vars_common_all_vm_svc_ipv4 }}"
provision_vm2_prefix: "{{ vars_common_all_vm_base_ipv4 }}"
provision_vm3_prefix: "{{ vars_common_all_vm_test_ipv4 }}"

proxmox_host: "{{ vars_common_all_pve_default_ipv4 }}:{{ vars_common_all_pve_default_port }}" 
proxmox_node: "{{ provision_vm_default_target_node }}"
proxmox_api_user: root
proxmox_api_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66396232616266636437656265313266336664666538393032353733383836323161316437653962
  3533316431633564653333626463343765353964313737630a653537373661653638656538656563
  30616539306563396564333230643139626565353531373033373039613035643464316465643333
  6334376161353230300a363434373037373962383339396637303532656264343433333336333336
  3662
