provision_connection_hcl_location: /root/pve.hcl
provision_dir: /root/provision
provision_vm_template_name: debian11

provision_vm_default_target_node:
provision_vm_gateway:
provision_vm_cidr:
provision_vm_nameserver:
provision_vm_searchdomain:
provision_vm1_hostgroup:
provision_vm2_hostgroup:
provision_vm3_hostgroup:
provision_vm1_prefix:
provision_vm2_prefix:
provision_vm3_prefix:

proxmox_host:
proxmox_node:
proxmox_api_user: root
proxmox_api_password:
